# Generated by Django 5.2.7 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_due_date_task_created_at_task_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesupload',
            name='file',
            field=models.FileField(upload_to='notes/'),
        ),
    ]
